### ISSUE TITLE
Mejora MVC

### ISSUE THREAD

**Issue by ejgutierrez74** [LuisJoseSanchez/aprende-php-con-ejercicios#2]
Buenas me gustaria comentarle dos cuestiones sobre el libro:

1 - En el apartado MVC, quiza deberia extenderse un poco mas con otro ejemplo y quiza utilizar un framework o dos ( Laravel, Codeigniter, Symphony...). Como instalarlos y como trabajar con ellos.

2 - En el apartado base de datos quiza incorporar postgres u otra base de datos.

3 - Algunos ejemplos o practicas nivell CFGS de DAW, algun ejercicio tipo listado de productos y carrito de compra con formulario login, o gestion de empleados de una empresa.

Gracias por su trabajo

**Comment by LuisJoseSanchez** [comment]
Hola, @ejgutierrez74

Estoy totalmente de acuerdo en todo lo que dices.

Un libro técnico que no se actualiza, poco a poco se va quedando anticuado, y a este libro de PHP le ha pasado eso mismo porque dejé de usarlo en clase hace mucho tiempo.

Lo ofrezco de forma gratuita por si le puede servir a alguien, pero es verdad que le hace falta un repaso en profundidad.

Si no me meto en otras historias durante un verano o unas vacaciones de Navidad, me gustaría ponerlo al día.

Un saludo
